import Head from 'next/head';
import Image from 'next/image';
import getAnime from '../lib/anime';
// import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { Anime } from '~/lib/types';
import Header from '../components/Header';
// import kitsu from './public/kitsu-svgrepo-com.svg';

// const montserrat = Montserrat({ weight: "400","700" })
// import {
//   faLightbulb,
//   faSun
// } from "@fortawesome/free-solid-svg-icons"

export async function getStaticProps() {
  const animeList = await getAnime();
  return {
    props: { animeList },
    revalidate: 3600000,
  };
}

const Home = ({ animeList }: { animeList: Anime[] }) => {
  return (
    <>
      <Head>
        <title>Shin</title>
        <Head>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/vercel.svg" />
        </Head>
      </Head>
      <main>
        <Header />
        <div className="flex justify-center my-16 text-white">
          <input
            type="text"
            placeholder="Search"
            className="border-2 border-white rounded-xl px-6 block bg-zinc-800 w-1/3 hover:scale-110 transition"
          />
          <button className="text-white ml-6 bg-zinc-800 hover:bg-zinc-700  p-3 rounded-xl transition">
            Search
          </button>
        </div>

        <article className="grid grid-cols-article gap-6 mx-24 justify-center">
          {animeList.map((anime) => {
            return (
              <section
                className="bg-zinc-800 rounded-xl text-white h-[540px] py-4 text-center"
                key={anime.title}
              >
                <div className="flex flex-col items-center justify-between h-full ">
                  <Image
                    src={anime.images.webp}
                    alt={anime.title}
                    height={200}
                    width={270}
                    className="rounded-xl grayscale hover:grayscale-0 hover:scale-105 transition"
                  ></Image>
                  <h1 className="text-lg w-5/6 hover:underline underline-offset-2 decoration-2 decoration-sky-500 cursor-pointer transition">
                    {anime.title.length > 50 ? anime.title.slice(0, 50) + "..." : anime.title}
                  </h1>
                  <ul className="flex justify-between w-5/6 text-black ">
                    <li className="bg-white h-[40px] w-[50px] rounded-lg flex justify-center items-center hover:scale-110 transition">
                      1d
                    </li>
                    <li className="bg-white h-[40px] w-[50px] rounded-lg flex justify-center items-center hover:scale-110 transition">
                      14h
                    </li>
                    <li className="bg-white h-[40px] w-[50px] rounded-lg flex justify-center items-center hover:scale-110 transition">
                      26m
                    </li>
                    <li className="bg-white h-[40px] w-[50px] rounded-lg flex justify-center items-center hover:scale-110 transition">
                      4s
                    </li>
                  </ul>
                </div>
              </section>
            );
          })}
          <section className="bg-zinc-800 rounded-xl text-white h-[540px] py-4 text-center">
            <div className="flex flex-col items-center justify-between h-full ">
              <Image
                src="https://cdn.myanimelist.net/images/anime/1297/133915l.jpg"
                alt="kimetsu no yaiba"
                height={200}
                width={270}
                className="rounded-xl grayscale hover:grayscale-0 hover:scale-105 transition"
              ></Image>
              <h1 className="text-lg w-5/6 hover:underline underline-offset-2 decoration-2 decoration-sky-500 cursor-pointer transition">
                Isekai de Cheat Skill wo Te ni Shita Ore wa, Genjitsu ...
              </h1>
              <ul className="flex justify-between w-5/6 text-black ">
                <li className="bg-white h-[40px] w-[50px] rounded-lg flex justify-center items-center hover:scale-110 transition">
                  1d
                </li>
                <li className="bg-white h-[40px] w-[50px] rounded-lg flex justify-center items-center hover:scale-110 transition">
                  14h
                </li>
                <li className="bg-white h-[40px] w-[50px] rounded-lg flex justify-center items-center hover:scale-110 transition">
                  26m
                </li>
                <li className="bg-white h-[40px] w-[50px] rounded-lg flex justify-center items-center hover:scale-110 transition">
                  4s
                </li>
              </ul>
            </div>
          </section>
        </article>
      </main>
    </>
  );
};

export default Home;
