import Head from 'next/head';
import Image from 'next/image';
// import kitsu from './public/kitsu-svgrepo-com.svg';

// const montserrat = Montserrat({ weight: "400","700" })

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className="flex justify-center h-12 pt-2">
          <ul className="flex justify-between w-1/4">
            <li>
              <a href="" className='text-bold'>MAL</a>
            </li>
            <li>
              <a href="">kitsu</a>
            </li>
            <li>
              <a href="">Anilist</a>
            </li>
            <li>Dark Mode</li>
          </ul>
        </header>
        <div className="flex justify-center my-16 text-black">
          <input
            type="text"
            placeholder="text"
            className="border-2 border-black rounded p-2 block w-1/5"
          />
          <button className='text-white ml-2'>Search</button>
        </div>

      <article className="grid grid-cols-article gap-6 mx-24 justify-center">
        <section className="bg-zinc-800 rounded-xl text-white h-[540px] py-4 text-center">
          <div className='flex flex-col items-center justify-between h-full '>
            <Image
              src="https://cdn.myanimelist.net/images/anime/1297/133915l.jpg"
              alt="kimetsu no yaiba"
              height={200}
              width={270}
              className="rounded-xl grayscale hover:grayscale-0 hover:scale-105 transition"
            ></Image>
          <h1 className='text-bold text-lg w-5/6 hover:underline underline-offset-2 decoration-2 decoration-sky-500 cursor-pointer transition'>Isekai de Cheat Skill wo Te ni Shita Ore wa, Genjitsu ...</h1>
          <ul className="flex justify-between w-3/4 text-black ">
              <li className="bg-white rounded-lg h-[40px] w-[50px]  text-bold flex justify-center items-center hover:scale-105 transition">1d</li>
              <li className="bg-white h-[40px] w-[50px] rounded-lg text-bold flex justify-center items-center hover:scale-105 transition">14h</li>
              <li className="bg-white h-[40px] w-[50px] rounded-lg  text-bold flex justify-center items-center hover:scale-105 transition">26m</li>
              <li className="bg-white h-[40px] w-[50px] rounded-lg  text-bold flex justify-center items-center hover:scale-105 transition">4s</li>
            </ul>
          </div>
          
        </section>
        <section className="bg-zinc-800 rounded-xl text-white h-[420px]"></section>
        <section className="bg-zinc-800 rounded-xl text-white h-[420px]"></section>
        <section className="bg-zinc-800 rounded-xl text-white h-[420px]"></section>
        <section className="bg-zinc-800 rounded-xl text-white h-[420px]"></section>
        {/* <section className="bg-blue-500 h-[400px]">Hello</section>
        <section className="bg-blue-500 h-[400px]">Hello</section>
        <section className="bg-blue-500 h-[400px]">Hello</section>
        <section className="bg-blue-500 h-[400px]">Hello</section>
        <section className="bg-blue-500 h-[400px]">Hello</section> */}
      </article>
      </main>
    </>
  );
};

export default Home;
